### ISSUE TITLE
Doesn't respect specifying gRPC port other than 8123

### ISSUE THREAD

**Issue by tdorzhi** [AxonIQ/axoniq-eventstore-client#11]
When client is configured with specified port other than 8123, AxonDBClient logs message:
`Received {hostname}:8123` then fails to connect to AxonDB.

This is required as we do integration tests with testcontainers and it maps container port with random ephemeral port

**Comment by fransvanbuul** [comment]
Hi!

The way the master/replica clustering mechanism in AxonDB works, is that
the client initially connects to a random node to get cluster info, and
that node will tell the client to which node it should actually connect for
data. This mechanism is also in place if you use a single AxonDB node.

A consequence of this, is that the AxonDB server has to know under which
hostname and port the clients can connect to it. Specifically, there are 3
properties:

# gRPC Port number of the AxonDB server to be used by clients
# axoniq.axondb.port=8123
#
# Hostname of the server, defaults to the hostname of the server. Used to
contruct the fully qualified hostname
# axoniq.axondb.hostname=
#
# Domain name added to the hostname when returning the fully qualified
hostname
# axoniq.axondb.domain=

My guess is that you didn't set axoniq.axondb.port in your case. I'm not
sure how you would get this to work if the port is chosen random. Somehow,
when booting AxonDB, you would have to 'know' this port.

If you have this info, there are many ways of getting this information to
AxonDB besides modifying the property file, since AxonDB support full
Spring externalized storage mechanism. So, for instance, you could also
pass these things as environment variables.

Feel free to reach out if you need any more support.

Kind regards,

*Frans van Buul*
AxonIQ <https://axoniq.io>
+31 6 5068 2984

<https://www.linkedin.com/in/frans-van-buul-8030743>
<https://twitter.com/Frans_vanBuul>

**Comment by tdorzhi** [comment]
> My guess is that you didn't set axoniq.axondb.port in your case. I'm not sure how you would get this to work if the port is chosen random. Somehow, when booting AxonDB, you would have to 'know' this port.

As of my knowledge, there is no way telling which port will be chosen by testcontainers

Is there a way to change such settings dynamically? As client I could tell server to change value of configuration for my needs.

**Comment by fransvanbuul** [comment]
There's no way of changing this dynamically when AxonDB is running.

I delved into TestContainers a little bit, and it appears there is a solution: the [FixedHostPortGenericContainer](https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/FixedHostPortGenericContainer.java).

If needed, you still may find an available port dynamically of course (like [this](https://gist.github.com/vorburger/3429822) maybe), and then passing that to the FixedHostPortGenericContainer as well as to AxonDB as an environment variable property.

**Comment by tdorzhi** [comment]
> I delved into TestContainers a little bit, and it appears there is a solution: the FixedHostPortGenericContainer.

Thank you so much! I don't know why I didn't see this type, this will definitely help me
As this helps to solve my problem, This issue can be closed

**Comment by bsideup** [comment]
@fransvanbuul 
FYI this solution ( "find an available port dynamically" ) will break on some envs (like CI where you run the tests inside a container), this is why we recommend not to use `FixedHostPortGenericContainer`.

If the port is configurable (especially with env vars), one could implement a container for AxonDB very much the same as we did with Kafka:
https://github.com/testcontainers/testcontainers-java/blob/master/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java

1) we start Socat on randomly exposed port
2) then we start target container and tell him to use the port we provide as **advertised** port (it still listens on the original port)

Let me know if you need some additional guidance :)
